name: Docker-build

on:
 workflow_run:
  workflows:
   - togo-front-end-build
  types:
   - completed

jobs:
  build-docker:
   runs-on: ubuntu-latest     
   if: ${{ github.event.workflow_run.conclusion == 'success' }}
   steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Get Full Image Name
      run: echo "FULL_IMAGE_NAME=${{secrets.ACR_LOGIN_SERVER}}/${{secrets.DOCKER_IMAGE_NAME}}:${{github.sha}}" >> $GITHUB_ENV

    - name: Build docker file
      run: |
        docker build \
        --build-arg VITE_CLOUD_HOST=${{ secrets.VITE_CLOUD_HOST }} \
        -t $FULL_IMAGE_NAME . 

    - name: Login into Azure Registry
      uses: docker/login-action@v4
      with:
        registry: ${{secrets.ACR_LOGIN_SERVER}}
        username: ${{secrets.ACR_USERNAME}}
        password: ${{secrets.ACR_PASSWORD}}

    - name: Push image into Azure
      run: docker push $FULL_IMAGE_NAME

    - name: Login into Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Create environment if dosen't exists
      run: |
          if az containerapp env show --name togo-environment --resources-group ${{ secrets.ACR_RESOURCE_GROUP }} > /dev/null 2>&1; then
            echo "Environment exits, Skipping environment creation"
          else 
            echo "Environment doesn't exists, Creating..."
            az containerapp env create \
            --name togo-environment \
            --resource-group ${{ secrets.ACR_RESOURCE_GROUP }} \
            --location southeastasia
          fi

    - name: Push to conatiner
      run: |
        az containerapp up \
        --name fron-end-react-container \
        --resource-group ${{secrets.ACR_RESOURCE_GROUP}} \
        --environment togo-environment \
        --location southeastasia \
        --image $FULL_IMAGE_NAME \
        --registry-server ${{secrets.ACR_LOGIN_SERVER}} \
        --registry-username ${{secrets.ACR_USERNAME}} \
        --registry-password ${{secrets.ACR_PASSWORD}} \
        --target-port 5173 \
        --ingress external \
        --env-vars \
          VITE_CLOUD_HOST=${{secrets.VITE_CLOUD_HOST}}

          
            
        
